# Book settings
title: "From Data to Insights: Tools for Data Science with Python"
author: "HDS team"
logo: "logo.png"  # Ensure this file is in the correct location

# Disable notebook execution temporarily
execute:
  execute_notebooks: "off"

# HTML-specific settings
html:
  baseurl: /Data-Science-Tools
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  theme:
    name: "sphinx_book_theme"
  # Other customizations can be added later

# Build settings
build:
  path_output: docs  # Ensure docs is used for GitHub Pages

# Table of contents
toc:
  number_sections: true

repository:
  url: https://github.com/ehsanx/Data-Science-Tools  # Your GitHub repository URL
  path_to_book: docs  # Path to the book in the repository, typically 'docs'
  branch: main  # The branch where the book is hosted (usually 'main')
